name: config
root: ~/projects/qubes/sys-config

windows:
  - main:
      layout: main-vertical
      panes:
        - nvim -S
  - scripts:
      root: ~/projects/qubes/sys-config/src/salt/user_salt/files/scripts
      panes:
        - nvim -S
