# /etc/zshrc is sourced in interactive shells.  It
# should contain commands to set up aliases, functions,
# options, key bindings, etc.
#

## shell functions
#setenv() { export $1=$2 }  # csh compatibility

# Set prompts
[[ "$PROMPT" = "%m%# " ]] && PROMPT='[%n@%m]%~%# '    # default prompt
#RPROMPT=' %~'     # prompt for right side of screen

bindkey -v               # vi key bindings
bindkey ' ' magic-space  # also do history expansion on space

# Provide pathmunge for /etc/profile.d scripts
pathmunge()
{
    if ! echo $PATH | /bin/grep -qE "(^|:)$1($|:)" ; then
        if [ "$2" = "after" ] ; then
            PATH=$PATH:$1
        else
            PATH=$1:$PATH
        fi
    fi
}

_src_etc_profile_d()
{
    #  Make the *.sh things happier, and have possible ~/.zshenv options like
    # NOMATCH ignored.
    emulate -L ksh


    # from bashrc, with zsh fixes
    if [[ ! -o login ]]; then # We're not a login shell
        for i in /etc/profile.d/*.sh; do
	    if [ -r "$i" ]; then
	        . $i
	    fi
        done
        unset i
    fi
}
_src_etc_profile_d

unset -f pathmunge _src_etc_profile_d

setopt auto_pushd # make cd use pushd automatically
setopt hist_ignore_all_dups # remove older duplicate entries from history
setopt hist_reduce_blanks # remove superfluous blanks from history items
setopt auto_cd # cd by typing directory name if it's not a command
#setopt correct_all # autocorrect commands
# completion
setopt auto_list # automatically list choices on ambiguous completion
setopt auto_menu # automatically use menu completion
setopt glob_complete # limit completions with globs
setopt menu_complete # fill suggestion on first tab (request)
setopt list_types # show tailing file types
setopt list_rows_first # horizontal movement by default
setopt always_to_end # move cursor to end if word had one match
# history
mkdir --parents "${HOME}/.cache/zsh" # zsh won't create dir, and hist isn't saved
HISTSIZE=20000 # make this at least 20% larger that SAVEHIST, else can't dedupe
SAVEHIST=10000
HISTFILE="${HOME}/.cache/zsh/history"
setopt inc_append_history # save history entries as soon as they are entered
setopt share_history # share history between different instances of the shell

alias reload="source ${HOME}/.zshrc && echo ZSH reloaded"

# You MUST source this, otherwise plug-ins won't install, and zinit command is undefined.
source ${MY_SCRIPTS}/init-zinit # won't run if template or root -- it installs plug-ins.

# SOURCES
[[ -f "${HOME}/.zsh/zle.zsh" ]] && source "${HOME}/.zsh/zle.zsh"

# remove duplicates from paths, this happens when re-sourcing zshrc
typeset -aU path
typeset -aU fpath

if [[ -n "`command -v starship`" ]]; then
  eval "$(starship init zsh)"
fi
